### ISSUE TITLE
Question/Documentation: robo.yml and command name mapping

### ISSUE THREAD

**Issue by pueppiblue** [consolidation/Robo#569]
For convenience reasons i want to define several command arguments for my command in robo.yml.
Right now i define them using the options array, since i don't know how to set arguments via robo.yml
[#570](https://github.com/consolidation/Robo/issues/570)

```
#RoboFile.php
public function cloneBranchToBuildDir(array $opts = ['repository' => InputOption::VALUE_REQUIRED]) 
{
  ...
}
```
```
#robo.yml
command:
  cloneBranchToBuildDir:
    options:
      repository: git@foobucket.bar:example/foo.git
```
Using 'cloneBranchToBuildDir' nor 'clone:branch-to-build-dir' works for passing the options to my command.
I can't find the corresponding name to use in the robo.yml. Using a "single atom" command name like `clonebranchtoworkdir` works fine but this is not optimal in my opinion.

Would you please point me to the correct notation for using camelCased command names inside the robo.yml?

**Comment by greg-1-anderson** [comment]
You cannot embed a `:` in a yaml identifier. Instead, represent your options as follows:
```
#robo.yml
command:
  clone:
    branch-to-build-dir:
      options:
        repository: git@foobucket.bar:example/foo.git
```
