### ISSUE TITLE
Question/Documentation: command arguments via robo.yml

### ISSUE THREAD

**Issue by pueppiblue** [consolidation/Robo#570]
For convenience reasons, having complete deployment configuration in one place, i want to define several command arguments for my command in robo.yml.
Right now i define them using the options array. But i'd rather use overridable arguments.

```
#RoboFile.php
public function cloneBranchToBuildDir(array $opts = ['repository' => InputOption::VALUE_REQUIRED]) 
{
  ...
}
```
```
#robo.yml
command:
  cloneBranchToBuildDir:
    options:
      repository: git@foobucket.bar:example/foo.git
```

Is there an option to define arguments for the command directly?
e.g.
```
#RoboFile.php
public function cloneBranchToBuildDir(string $repository) 
{
  ...
}
```
```
#robo.yml
command:
  cloneBranchToBuildDir:
    arguments:
      repository: git@foobucket.bar:example/foo.git
```
