### ISSUE TITLE
replace text if text not found.

### ISSUE THREAD

**Issue by michaelpporter** [consolidation/Robo#610]
### Steps to reproduce
What did you do?

I want to find text and in a file and replace it if the text does not already exist.

### Expected behavior
Tell us what should happen

``` php
if (!$this->taskFindInFile('../traefik.yml')->search('- bob')) {
    $this->taskReplaceInFile('../traefik.yml')
      ->from('# network-new')
      ->to('# network-new
      - bob') // adds a new network to the YAML file. I do not want duplicates.
      ->run();
}
```

### Actual behavior
Tell us what happens instead

There is no find in file to check for existing text, that I know of.

### System Configuration
Which O.S. and PHP version are you using?

macOS 10.12 php 7

**Comment by greg-1-anderson** [comment]
Maybe [taskReplaceInFile](http://robo.li/tasks/File/#replace) does about what you are looking for. However, I'd think you'd be much better off with a YAML parser than a text processor for this use-case.

**Comment by michaelpporter** [comment]
A YAML parser would be great. I am trying to setup a common docker container to add / remove networks as part of a project setup. 

looking for a nice flow that allow a Developer clones repo and runs `robo setup` which setups the network, runs composer, npm, starts the stack etc.

Here is what I have so far, it's working but ugly.

``` php

  /**
   * Testing replace in file.
   */
  public function tfkSetup() {
    $this->taskReplaceInFile('../traefik.yml')
      ->from('# network-new')
      ->to('# network-new
      - site')
      ->run();

    $this->taskReplaceInFile('../traefik.yml')
      ->from('# new-network')
      ->to('# new-network
  site:
    external:
      name: site_default')
      ->run();
    $this->_exec("docker-compose -f ../traefik.yml up -d");
  }

  /**
   * Testing replace in file.
   */
  public function tfkClean() {
    $this->taskReplaceInFile('../traefik.yml')
      ->regex('~(.*)- site\n~')
      ->to('')
      ->run();
    $this->taskReplaceInFile('../traefik.yml')
      ->regex('~(.*)site:\n(.*)external:\n(.*)site_default\n~')
      ->to('')
      ->run();
    $this->_exec("docker-compose -f ../traefik.yml up -d");
  }
```

**Comment by greg-1-anderson** [comment]
The output formatters project has all sorts of cool ways to write data, and of course symfony/yaml can parse yaml. dflydev/dot-access-data gives you a cool way to address nested elements in an array. All of these packages are already dependencies of Robo.

I can imagine something like:
```
$this->taskData('../traefik.yml')
  ->loadYaml()
  ->set('site.external.name', $siteName)
  ->saveYaml()
  ->run();
```

Append, delete and move operations could also be handy. Your implementation may vary. PRs welcome.

**Comment by michaelpporter** [comment]
Thanks for the tip. Here is what I end up with. I can try to make it a function and add a PR.

```php
<?php

use Dflydev\DotAccessData\Data;
use Symfony\Component\Yaml\Yaml;

class RoboFile extends \Robo\Tasks {

  /**
   * Testing replace in file.
   */
  public function tfkSetup() {
    $yml = Yaml::parse(file_get_contents('../traefik.yml'));
    $data = new Data($yml);

    $exists = $data->get('services.traefik.networks');

    if (!in_array('bob',$exists)) {
      $exists[] = 'bob';
    }
    $exists = array_values($exists);
    $data->set('services.traefik.networks', $exists);

    $exists = $data->has('networks.bob.external.name');
    if (!$exists) {
      $data->set('networks.bob.external.name', 'bob_default');
    }

    $yaml = Yaml::dump($data->export(),5);

    file_put_contents('../traefik.yml', $yaml);
  }

  /**
   * Testing replace in file.
   */
  public function tfkClean() {
    $yml = Yaml::parse(file_get_contents('traefik.yml'));
    $data = new Data($yml);
    $exists = $data->get('services.traefik.networks');
    if(($key = array_search('bob', $exists)) !== false) {
      unset($exists[$key]);
    }
    $exists = array_values($exists);
    $data->set('services.traefik.networks', $exists);

    $exists = $data->has('networks.bob.external.name');
    if ($exists) {
      $data->remove('networks.bob');
    }
    $yaml = Yaml::dump($data->export(),5);

    file_put_contents('../traefik.yml', $yaml);
  }

}

```
Starting Yaml file
```
version: '2'
services:
    traefik:
        image: traefik
        restart: unless-stopped
        command: '-c /dev/null --web --docker --logLevel=DEBUG'
        networks:
            - tom
            - sites
            - site2
        ports:
            - '80:80'
            - '8080:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
    portainer:
        image: portainer/portainer
        command: '--no-auth'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        labels:
            - traefik.backend=portainer
            - traefik.port=9000
            - 'traefik.frontend.rule=Host:portainer.docker.localhost'
networks:
    tom:
        external:
            name: tom_default
    sites:
        external:
            name: sites_default
    site2:
        external:
            name: site2_default

```
