### ISSUE TITLE
Static analysis

### ISSUE THREAD

**Issue by szepeviktor** [consolidation/Robo#909]
```bash
composer require --dev phpstan/phpstan:^0.9.0
vendor/bin/phpstan analyze --level=0 -c phpstan.neon src/
```

then raise Level one by one

`phpstan.neon`

```yaml
parameters:
    level: max
    ignoreErrors:
        # Uses func_get_args()
        - '#^Method Robo\\Tasks::task\(\) invoked with [12345] parameters?, 0 required\.$#'
```

Thank you for considering!
See my recent PR-s.
